# Generated by Django 3.1.3 on 2020-12-02 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0005_auto_20201201_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerevent',
            name='game',
        ),
        migrations.AddField(
            model_name='gamerevent',
            name='gamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='levelupapi.gamer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamerevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='levelupapi.event'),
        ),
    ]
